[package]
name = "software-renderer-rs"
version = "0.1.0"
authors = ["Bjorn Martens <bjorn@expeditious.nl>"]
edition = "2018"
build="build.rs"

[dependencies]
libc = "0.2.0"

[build-dependencies]
cmake = "0.1.42"
